import { useEffect, useState } from 'react';
import DateTimePicker from './DateTimePicker';

type WindowItem = { id: string; name: string; link_id?: string; starts_at: string; ends_at: string; recurrence?: string; reason?: string; enabled?: boolean };
type Link = { id: string; link_name: string };
const auth = () => { const token = localStorage.getItem('netops_token'); return token ? { Authorization: `Bearer ${token}` } : {}; };
const localInput = (value?: string) => value ? new Date(value).toISOString().slice(0, 16) : '';

const WanMaintenanceEditPanel: React.FC = () => {
  const [items, setItems] = useState<WindowItem[]>([]);
  const [links, setLinks] = useState<Link[]>([]);
  const [selectedId, setSelectedId] = useState('');
  const [form, setForm] = useState({ name: '', link_id: '', starts_at: '', ends_at: '', recurrence: 'once', reason: '' });
  const [message, setMessage] = useState('');
  const load = async () => { const [windows, wanLinks] = await Promise.all([fetch('/api/monitoring/wan-maintenance-windows', { headers: auth() }), fetch('/api/monitoring/wan-links?page_size=100', { headers: auth() })]); if (windows.ok) setItems((await windows.json()).items || []); if (wanLinks.ok) setLinks((await wanLinks.json()).items || []); };
  useEffect(() => { void load(); }, []);
  const select = (id: string) => { const item = items.find((candidate) => candidate.id === id); setSelectedId(id); if (item) setForm({ name: item.name || '', link_id: item.link_id || '', starts_at: localInput(item.starts_at), ends_at: localInput(item.ends_at), recurrence: item.recurrence || 'once', reason: item.reason || '' }); };
  const save = async () => { if (!selectedId || !form.name || !form.starts_at || !form.ends_at || new Date(form.ends_at) <= new Date(form.starts_at)) { setMessage('请选择窗口并填写有效时间'); return; } const response = await fetch(`/api/monitoring/wan-maintenance-windows/${encodeURIComponent(selectedId)}`, { method: 'PATCH', headers: { ...auth(), 'Content-Type': 'application/json' }, body: JSON.stringify({ ...form, starts_at: new Date(form.starts_at).toISOString(), ends_at: new Date(form.ends_at).toISOString() }) }); setMessage(response.ok ? '维护窗口已更新' : '维护窗口更新失败'); if (response.ok) void load(); };
  return <section className="mt-4 rounded-2xl border border-[var(--card-border)] bg-[var(--card-bg)] p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><h3 className="text-sm font-extrabold text-[var(--app-text)]">维护窗口编辑</h3><p className="mt-1 text-[10px] text-[var(--muted-text)]">修改范围、时间、周期和原因；删除仍由上方列表执行。</p></div>{message && <span className="text-xs text-cyan-700">{message}</span>}</div><div className="mt-3 grid gap-2 md:grid-cols-3"><select value={selectedId} onChange={(event) => select(event.target.value)} className="rounded-lg border border-[var(--card-border)] bg-[var(--card-bg)] px-2 py-2 text-xs"><option value="">选择已有维护窗口</option>{items.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.starts_at}</option>)}</select><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} placeholder="窗口名称" className="rounded-lg border border-[var(--card-border)] bg-[var(--card-bg)] px-2 py-2 text-xs" /><select value={form.link_id} onChange={(event) => setForm({ ...form, link_id: event.target.value })} className="rounded-lg border border-[var(--card-border)] bg-[var(--card-bg)] px-2 py-2 text-xs"><option value="">全站点/全链路</option>{links.map((link) => <option key={link.id} value={link.id}>{link.link_name}</option>)}</select><DateTimePicker value={form.starts_at} onChange={(value) => setForm({ ...form, starts_at: value })} language="zh" placeholder="选择开始时间" /><DateTimePicker value={form.ends_at} onChange={(value) => setForm({ ...form, ends_at: value })} language="zh" placeholder="选择结束时间" /><select value={form.recurrence} onChange={(event) => setForm({ ...form, recurrence: event.target.value })} className="rounded-lg border border-[var(--card-border)] bg-[var(--card-bg)] px-2 py-2 text-xs"><option value="once">一次性</option><option value="daily">每日</option><option value="weekly">每周</option><option value="monthly">每月</option></select><input value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} placeholder="维护原因" className="rounded-lg border border-[var(--card-border)] bg-[var(--card-bg)] px-2 py-2 text-xs md:col-span-2" /></div><button type="button" onClick={() => void save()} className="mt-3 rounded-lg bg-amber-600 px-3 py-2 text-xs font-bold text-white">保存修改</button></section>;
};

export default WanMaintenanceEditPanel;
