#!/bin/sh
set -eu

readonly SOURCE_DIST=/app/frontend-dist
readonly SHARED_DIST=/app/dist
readonly MONITORING_DEFAULTS=/app/monitoring-defaults
readonly MONITORING_RUNTIME=/app/artifacts/monitoring/runtime

mkdir -p "$SHARED_DIST/assets"

# Hashed assets are copied first and never deleted. This keeps an old
# index.html usable while a rolling restart is updating the shared volume.
if [ -d "$SOURCE_DIST/assets" ]; then
    cp -a "$SOURCE_DIST/assets/." "$SHARED_DIST/assets/"
fi

# Vite currently emits only index.html and assets/, but preserve any future
# root-level output files as well. Publish index.html last and atomically.
find "$SOURCE_DIST" -mindepth 1 -maxdepth 1 ! -name assets ! -name index.html -exec cp -a {} "$SHARED_DIST/" \;
index_tmp="$SHARED_DIST/.index.html.$$"
cp -a "$SOURCE_DIST/index.html" "$index_tmp"
mv -f "$index_tmp" "$SHARED_DIST/index.html"

# Seed or refresh the shared collector runtime when no versioned artifact is published.
# A published artifact replaces this directory atomically with current_version.json;
# never overwrite a versioned artifact, but keep default baseline in sync with code updates.
if [ ! -f "$MONITORING_RUNTIME/current_version.json" ]; then
    mkdir -p "$MONITORING_RUNTIME"
    cp -a "$MONITORING_DEFAULTS/." "$MONITORING_RUNTIME/"
else
    # Keep vmagent scrape config in sync while preserving materialized targets
    mkdir -p "$MONITORING_RUNTIME/vmagent/targets"
    if [ -f "$MONITORING_DEFAULTS/vmagent/scrape.yml" ]; then
        cp -f "$MONITORING_DEFAULTS/vmagent/scrape.yml" "$MONITORING_RUNTIME/vmagent/scrape.yml"
    fi
    if [ ! -f "$MONITORING_RUNTIME/vmagent/targets/linux_targets.yml" ] && [ -f "$MONITORING_DEFAULTS/vmagent/targets/linux_targets.yml" ]; then
        cp -f "$MONITORING_DEFAULTS/vmagent/targets/linux_targets.yml" "$MONITORING_RUNTIME/vmagent/targets/linux_targets.yml"
    fi
    if [ ! -f "$MONITORING_RUNTIME/vmagent/targets/windows_targets.yml" ] && [ -f "$MONITORING_DEFAULTS/vmagent/targets/windows_targets.yml" ]; then
        cp -f "$MONITORING_DEFAULTS/vmagent/targets/windows_targets.yml" "$MONITORING_RUNTIME/vmagent/targets/windows_targets.yml"
    fi
fi

# Existing named volumes can contain artifacts generated by an older compiler.
# Normalize only the shared runtime copy before the exporter reads it; this is
# an idempotent compatibility migration and never prints credential values.
PYTHONPATH=/app/backend python -m services.monitoring_runtime_normalizer \
    --root "$MONITORING_RUNTIME"

exec uvicorn backend.main:app \
    --host 0.0.0.0 \
    --port 8003 \
    --workers "${WORKERS:-1}" \
    --timeout-graceful-shutdown 20
